Additional information to help installation failures.

diff --git a/build_sd b/build_sd
--- a/build_sd
+++ b/build_sd
@@ -105,6 +105,7 @@ configure_boot_partition()
 {
     if is_root; then
         # Work with boot partition:
+        echo "[32;1mMounting boot partition /dev/${Target}1 to mpoint[m"
         mount /dev/"$Target"1 mpoint
         cp wpa_supplicant.conf mpoint
         touch mpoint/ssh
@@ -118,6 +119,7 @@ configure_root_partition()
 {
     if is_root; then
         cp load_apps mpoint/home/pi/load_apps
+        cp bash_profile mpoint/home/pi/.bash_profile
         # ./config_bluetooth
     fi
 }
@@ -130,25 +132,27 @@ configure_sd_card()
 
     if is_root; then
         # Work with boot partition:
-        echo "[33;1mMounting the boot partition.[m"
+        echo "[33;1mMounting the boot partition /dev/${Target}1 to mpoint.[m"
         mount /dev/"$Target"1 mpoint
         if [ "$?" -eq 0 ]; then
             configure_boot_partition
             sync
             umount mpoint
 
-            echo "[33;1mMounting the root partition.[m"
+            echo "[33;1mMounting the root partition /dev/${Target}2 to mpoint.[m"
             mount /dev/"$Target"2 mpoint
             if [ "$?" -eq 0 ]; then
                 configure_root_partition
                 sync
                 umount mpoint
             else
-            echo "Failed to mount /dev/${Target}2, error code $?"
+                echo "Failed to mount /dev/${Target}2, error code $?"
+                lsblk
             fi
 
         else
             echo "Failed to mount /dev/${Target}1, error code $?"
+            lsblk
         fi
 
 
