Many changes, latest removing notification stuff.

diff --git a/build_sd b/build_sd
--- a/build_sd
+++ b/build_sd
@@ -7,9 +7,75 @@ show_usage()
     echo
     echo "build_sd [name of device]"
     echo "example: [32;1m./build_sd sda[m"
+    echo
+    echo "If you want to enable nc communication, add an extra parameter,"
+    echo "the socket port, from 1025 to 65535.  It's up to you to pick an"
+    echo "appropriate port number."
+    echo
+    echo "example: [32;1m./build_sd sda 12345[m."
 }
 
 is_root() { [ "$USER" = "root" ]; }
+
+un_mount()
+{
+    local IFS=$'\n'
+    local -a lines=( $( mount | grep "$Target" ) )
+    local line
+    local -a mounting
+
+    local mpath mmount
+
+    IFS=$' '
+    for line in "${lines[@]}"; do
+        mounting=( $line )
+        mpath="${mounting[0]}"
+        mmount="${mounting[2]}"
+        echo "Unmounting [32;1m${mpath}[m at mount point [32;1m${mmount}[m"
+        umount "${mmount}"
+    done
+}
+
+is_local_ip()
+{
+    local IFS=$'.'
+    local -a ip=( $1 )
+
+    if [ "${#ip[@]}" -ne 4 ]; then
+       return 1
+    fi
+
+    local -i v1="${ip[0]}"
+    local -i v2="${ip[1]}"
+
+     if [ "$v1" -eq 10 ]; then
+         return 0
+     elif [ "$v1" -eq 192 ] && [ "$v2" -eq 168 ]; then
+         return 0
+     elif [ "$v1" -eq 172 ] && [ "$v2" -ge 16 ] && [ "$v2" -le 31 ]; then
+         return 0
+     else
+         return 1
+     fi
+}
+
+get_local_ip()
+{
+    local IFS=$'\n'
+    local -a nifs ninfo
+    local nif
+
+    nifs=( $( ip -o -4 addr | awk '{ print $1 " " $3 }' - ) )
+    for nif in "${nifs[@]}"; do
+        ninfo=( $nif )
+        if is_local_ip "${ninfo[1]}"; then
+            echo "${ninfo[1]}"
+            return 0
+        fi
+    done
+
+    return 1
+}
 
 confirm_Target()
 {
@@ -53,20 +119,34 @@ copy_image()
 {
     local path_img="$1"
     local -a args=(
-        bs=4M
+        bs=10M
         if="${path_img}"
         of="/dev/${Target}"
         status=progress
         conv=fsync
     )
 
-    echo "Using arguments: [32;1m${args[*]}[m"
-
     if is_root; then
-        sudo dd "${args[@]}"
-        if [ $? -eq 0 ]; then
-            return 0
+        echo "Unmounting partitions, if necessary"
+        un_mount
+        
+        echo "Wiping existing contents of SD card"
+        wipefs -a "/dev/${Target}"
+        if [ $? -eq 0 ];then
+
+            echo "Calling dd using arguments: [32;1m${args[*]}[m"
+            dd "${args[@]}"
+            if [ $? -eq 0 ]; then
+                sync
+                echo "Successfully copied the image to the sd card."
+                return 0
+            else
+                echo "Unexpected failure loading image to the sd card."
+            fi
+        else
+            echo "wipefs failed, operation aborted."
         fi
+
     else
         echo "Failed to copy image: must be root."
     fi
@@ -104,9 +184,6 @@ get_boot_partition()
 configure_boot_partition()
 {
     if is_root; then
-        # Work with boot partition:
-        echo "[32;1mMounting boot partition /dev/${Target}1 to mpoint[m"
-        mount /dev/"$Target"1 mpoint
         cp wpa_supplicant.conf mpoint
         touch mpoint/ssh
         echo "[33;1mDo not forget to set SSH with [34;1mraspi-config[33;1m upon first boot.[m"
@@ -115,17 +192,76 @@ configure_boot_partition()
     fi
 }
 
+add_load_apps_to_rc_local()
+{
+    local target=mpoint/etc/rc.local
+    local -a seds=(
+        '/^exit 0/i '
+        'sudo chown pi:pi /home/pi/* # DELETE\n'
+        'sudo /etc/init.d/load_apps  # DELETE\n'
+        'sudo sed -i -E '
+        "'/^.*# DELETE$/d' "
+        '/etc/rc.local  # DELETE\n'
+        )
+
+    local IFS=$''
+    sed -i "${seds[*]}" $target
+}
+
+prepare_home_directory()
+{
+    local pwd="$PWD"
+    cd mpoint/home/pi
+
+    mkdir Downloads
+    cp "$pwd/build_firewall" .
+
+    cd "$pwd"
+}
+
+set_us_keyboard()
+{
+    sed -E -i 's/KBLAYOUT="[[:alnum:]]{2}"/KBLAYOUT="us"/' "$RASPI_ROOT/etc/default/keyboard"
+}
+
 configure_root_partition()
 {
+    local target=mpoint/etc/init.d
     if is_root; then
-        cp load_apps mpoint/home/pi/load_apps
-        cp bash_profile mpoint/home/pi/.bash_profile
+        echo "Copying load_apps script to [32;1m${target}[m right now."
+        cp load_apps "${target}/load_apps"
+
+        prepare_home_directory
+        set_us_keyboard
+
+        # Do this last, because rc.local will chown the contents
+        # of /home/pi so the scripts can be run as user 'pi'.
+        add_load_apps_to_rc_local
+
+        # enable_ssh
         # ./config_bluetooth
     fi
 }
 
+enable_ssh()
+{
+    local sshname
+    local curdir="$PWD"
+    cd "${startingdir}/mpoint/etc/rc2.d"
+
+    sshname=$( ls | grep "K[[:digit:]]{2}ssh" )
+    if [ "$?" -eq 0 ]; then
+        mv "$sshname" "S${sshname:1}"
+    fi
+
+    cd "$curdir"
+}
+
+
 configure_sd_card()
 {
+    local RASPI_ROOT
+    
     if ! [ -d mpoint ]; then
         mkdir mpoint
     fi
@@ -142,6 +278,7 @@ configure_sd_card()
             echo "[33;1mMounting the root partition /dev/${Target}2 to mpoint.[m"
             mount /dev/"$Target"2 mpoint
             if [ "$?" -eq 0 ]; then
+                RASPI_ROOT="${PWD}/mpoint"
                 configure_root_partition
                 sync
                 umount mpoint
@@ -186,13 +323,18 @@ declare startingdir="$PWD"
 declare image
 
 if confirm_Target; then
+
     image=$( get_image_filename )
     if [ $? -eq 0 ]; then
         copy_image "$image"
+
         if [ $? -eq 0 ]; then
             configure_sd_card
         fi
+        un_mount
     fi
 else
     echo "Suspicious target"
 fi
+
+echo "Compare pre- and post-raspi-config files in /etc/ssh for how SSH is configured"
